#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = uwsm app -- waybar
exec-once = ~/.local/bin/handle-monitors.sh
exec-once = ~/dotfiles/scripts/switcher.sh
exec-once = uwsm app -- wl-clip-persist --clipboard regular
