
#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors
env = HYPRCURSOR_SIZE,24
exec-once = hyprctl setcursors catppuccin-mocha-dark-cursors 24

env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;wcb
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland

env = XDG_CURRENT_SESSION,Hyprland
env = XDG_SESSION_SESSION,Hyprland

