permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, input-capture, allow
permission = /usr/bin/grim, screencopy, allow
# permission = *deskflow*, input-capture, allow
