# Tag floating apps
windowrule = tag +floating-window, match:class (blueman-manager|float.Impala|float.Wiremix|org.gnome.NautilusPreviewer)
windowrule = tag +floating-window, match:class (xdg-desktop-portal-gtk|DesktopEditors|org.gnome.Nautilus), match:title ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files)

# Tag Videocall apps
windowrule = tag +videocall, match:class .*meet.google.com.* # Google Meet PWA
windowrule = tag +videocall, match:class Slack match:title .*Junta.* # Slack Huddles (Junta in Spanish)

# Tag Code Editors
windowrule = tag +codeeditor, match:class (codium|code|.*zed.*) # VSCodium, VSCode and Zed editor

# Tag Terminal Emulators
windowrule = tag +terminal, match:class .*tty.*

# Tag Internet Browsers
windowrule = tag +browser, match:class (.*zen|chromium-browser)
windowrule = tag +browser, match:initial_title (.*Chromium.*)

# Tag Mail app
windowrule = tag +mail, match:class (chrome-mail.notion.so*)

# Tag Calendar app
windowrule = tag +calendar, match:class (chrome-calendar.notion.so*)
