##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules


workspace = 7, persistent:true  # Mail and Calendar workspace
workspace = 8, persistent:true  # Notion (Cohesion) workspace
workspace = 9, persistent:true  # Slack workspace

# windowrule = workspace 7, match:tag calendar
# windowrule = workspace 7, match:tag mail
windowrule = workspace 7, match:tag llm
windowrule = workspace 8, match:tag notion
# windowrule = workspace 9, match:class Slack

# exec-once = [workspace 7 silent] uwsm app -- chromium-browser --disable-features=WaylandWpColorManagerV1 --app="https://mail.notion.so"
exec-once = [workspace 7 silent] uwsm app -- helium --disable-features=WaylandWpColorManagerV1 --app="https://claude.ai"
exec-once = [workspace 8 silent] uwsm app -- helium --disable-features=WaylandWpColorManagerV1 --app="https://notion.so"
# exec-once = [workspace 8 silent] uwsm app -- flatpak run io.github.brunofin.Cohesion
exec-once = [workspace 9 silent] uwsm app -- slack --enable-features=UseOzonePlatform --ozone-platform=wayland
