workspace = 6, persistent:true # Video Calls workspace

windowrule = tag +videocall, class:.*meet.google.com.* # Google Meet PWA
windowrule = tag +videocall, class:Slack title:.*Junta.* # Slack Huddles (Junta in Spanish)

windowrule = opacity 1.0 1.0, tag:videocall
windowrule = workspace 6, tag:videocall
