##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

workspace = 1, persistent:true  # Browser workspace
workspace = 2, persistent:true  # Editor (vscode) workspace
workspace = 3, persistent:true  # Terminal (ghostty) workspace

windowrule = workspace 1, match:tag browser
windowrule = workspace 2, match:tag codeeditor
windowrule = workspace 3, match:tag terminal

exec-once = [workspace 1 silent] uwsm app -- helium
exec-once = [workspace 2 silent] uwsm app -- zed
exec-once = [workspace 3 silent] uwsm app -- ghostty
# exec-once = [workspace 4 silent] uwsm app -- input-leap --config "~/.config/input-leap.conf" --daemon
