##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
	name = supress-maximize-events
	suppress_event = maximize 
	match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
	name = fix-xwayland-drags
	no_focus = true
	match:class = ^$
	match:title = ^$
	match:xwayland = true
	match:float = true
	match:fullscreen = false
	match:pin = false
}

# Hyprland-run windowrule
windowrule {
	name = move-hyprland-run
	match:class = hyprland-run
	move = 20 monitor_h-120
	float = yes
}

workspace = 1, persistent:true  # Browser workspace
workspace = 2, persistent:true  # Editor (vscode) workspace
workspace = 3, persistent:true  # Terminal (ghostty) workspace

windowrule = workspace 1, match:tag browser
windowrule = workspace 2, match:tag codeeditor
windowrule = workspace 3, match:tag terminal

exec-once = [workspace 1 silent] uwsm app -- flatpak run app.zen_browser.zen 
exec-once = [workspace 2 silent] uwsm app -- codium --enable-features=UseOzonePlatform --ozone-platform=wayland
exec-once = [workspace 3 silent] uwsm app -- ghostty
exec-once = [workspace 4 silent] uwsm app -- input-leap --config "~/.config/input-leap.conf" --daemon
