#!/bin/bash

sudo rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h\n" | sudo tee -a /etc/yum.repos.d/vscodium.repo

sudo dnf install -y codium

codium --install-extension ms-toolsai.jupyter
codium --install-extension aaron-bond.better-comments
codium --install-extension catppuccin.catppuccin-vsc
codium --install-extension catppuccin.catppuccin-vsc-icons
codium --install-extension christian-kohler.path-intellisense
codium --install-extension mechatroner.rainbow-csv
codium --install-extension ms-python.python
codium --install-extension ms-python.debugpy
codium --install-extension ms-toolsai.jupyter-renderers
codium --install-extension ms-toolsai.jupyter-keymap
codium --install-extension ms-toolsai.vscode-jupyter-cell-tags
codium --install-extension charliermarsh.ruff
codium --install-extension ms-toolsai.vscode-jupyter-slideshow
codium --install-extension tamasfe.even-better-toml
codium --install-extension yzhang.markdown-all-in-one
codium --install-extension github.vscode-pull-request-github
